### ISSUE TITLE
add arpeggio

### ISSUE THREAD

**Issue by sugizo** [mikehadlow/gtr-cof#58]
the idea is to show the chord tone on fretboard that can be use to play arpeggio, something similar like the scale, but only show the chord tone 
**e.g. for major arpeggio (semitone : 0-4-7, degree : 1-3-5)**
**music-module.ts** (not sure you want to implement this on the same module or create new)

        { name: "Major", intervals: new mod.Mod([true, false, false, false, true, false, false, true, false, false, false, false]), modes: [{ name: 'Major', index: 0}], defaultModeIndex: 0 },

thanks

**Comment by mikehadlow** [comment]
Not sure I understand? Guitar dashboard already does that when you select a chord?

**Comment by sugizo** [comment]
Q: Guitar dashboard already does that when you select a chord?
A: hm 50-50 i think, the current code show the chord tone with another tone that is part of the scale, the advantage to add arpeggio are :
- guitarist can focus just the chord tone on fretboard
- it more support of the chord, let say, augmented, diminished, suspended, dominant, major, minor and it's variation (6th, 7th)
with current code, it just support either major or minor

the idea is base on https://fretboarder.app
when you click it shows major arpeggio on fretboard that is consist R (root note) -3-5 and it's note (A-C#-E)

the author created more complex, can combine between (scale + scale), (scale + chord), etc (more than 2 elements combination e.g. (chord+scale+chord) ), which is enlarge the idea to make improvisation

base on experience it's rarely use all of the tone that provide by scale, some used, some not
here's my local modification for chord, if you interest to implement, i'll send the code, thanks

![screen_shot](https://user-images.githubusercontent.com/2418295/92722552-f980d980-f391-11ea-97b2-0c2a0383597b.png)

**Comment by mikehadlow** [comment]
My intention with Guitar Dashboard was to provide a "music theory explorer for guitarists", not necessarily a catalogue of chords etc. Showing the chord as part of a scale is exactly what GD is meant to do. The numbered buttons in the very centre are there so you can add and remove chord degrees. Here's is it displaying what you asking for above:
![image](https://user-images.githubusercontent.com/223097/92903570-182ab300-f41a-11ea-99cc-494d7a01058d.png)
Thanks for showing me fretboarder.app, it looks really nice, especially the feature that allows you to combine scales/chords. I think their intention is very much to act as a catalogue. You can see this in the different approaches to how we have coded our apps. fretboarder.app simply hard codes chords as interval sets, as you can see in this code file: [music.js](https://github.com/cheap-glitch/fretboarder/blob/main/src/modules/music.js). There's is nothing like that in GD because the chords are generated by an algorithm.
